### ISSUE TITLE
Access i18n values in controller

### ISSUE THREAD

**Issue by andykrier** [bigskytech/ember-todo#1]
There is a bug in the ember-cli-i18n module that is preventing us from accessing the translations outside of the template.

https://github.com/dockyard/ember-cli-i18n/issues/9

**Comment by matk0** [comment]
Hi guys, it's been a couple of months. How do I access i18n values in my tests?
I tried `import t from 'ember-cli-i18n/utils/t';` but then `t('home.title')` is returning `undefined` even thought I got it defined
```
export default {
  home: {
    title: 'Vitaj na unpollute.it'
  }
};
```
